### ISSUE TITLE
microsoft r open

### ISSUE THREAD

**Issue by brianbolt** [jeffreyhorner/rapache#38]
Hi,
Is it possible to install rapache using microsoft r open instead of R-devel?  Currently I get errors about R-devel requirements.

Thanks

**Comment by jeffreyhorner** [comment]
Huh, haven't looked into it, but rapache is intended on unix-like os's, not windows.

**Comment by brianbolt** [comment]
Microsoft R open (MRO) is available for Linux  distributions as well as Mac
and Windows.

https://mran.revolutionanalytics.com/download/

Sent from my iPhone
On Mar 10, 2016, at 6:45 AM, jeffreyhorner <notifications@github.com> wrote:

Huh, haven't looked into it, but rapache is intended on unix-like os's, not
windows.

—
Reply to this email directly or view it on GitHub
<https://github.com/jeffreyhorner/rapache/issues/38#issuecomment-194880809>.
