### ISSUE TITLE
Process or memory?

### ISSUE THREAD

**Issue by patrickmcconnell** [jeffreyhorner/rapache#41]
Does R remain memory resident or is it loaded for each request?

If the former, is it possible to load a dataset once in memory and then perform some work on it for each request?

**Comment by jeffreyhorner** [comment]
First it's important to understand the server architecture. Traditionally for the prefork multi-process-module (MPM) there's a parent process that spawns many child processes to handle incoming connections, and these children have varying lifetimes: children go away after a number of requests, and new children are spawned.

When a child is spawned, a new R interepreter is initialized, and once an R related request comes in various R codes can be run in the child process depending on the apache configuration files. Any mutation that happens to *that* child will stick around for its lifetime.

*BUT*, there are no guarantees that consecutive requests even from the same client will always go back to the same child process, so your R code ought to be written for this case.

**Comment by patrickmcconnell** [comment]
Thanks!
