### ISSUE TITLE
Installing RApache in Ubuntu 16.04 Apache/2.4.18 (Ubuntu): I get some errors

### ISSUE THREAD

**Issue by rplana6** [jeffreyhorner/rapache#43]
Hi Jeffrey,

I am trying to install RApache in Ubuntu 16.04 Apache/2.4.18 (Ubuntu) but I get some errors:

1- First when i install some packages:

sudo apt-get install apache2-prefork-dev apache2-mpm-prefork libapreq2-dev r-base-dev

I get an error message:

Package apache2-mpm-prefork is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source

E: Unable to locate package apache2-prefork-dev E: Package 'apache2-mpm-prefork' has no installation candidate

When I try

debuild -us -uc

I get the message:

This package has a Debian revision number but there does not seem to be an appropriate original tar file or .orig directory in the parent directory; (expected one of libapache2-mod-r-base_1.2.8.orig.tar.gz, libapache2-mod-r-base_1.2.8.orig.tar.bz2, libapache2-mod-r-base_1.2.8.orig.tar.lzma, libapache2-mod-r-base_1.2.8.orig.tar.xz or rapache.orig) continue anyway? (y/n)

I decide for yes but it does not work, I get:

dpkg-buildpackage -rfakeroot -D -us -uc dpkg-buildpackage: warning: using a gain-root-command while being root dpkg-buildpackage: source package libapache2-mod-r-base dpkg-buildpackage: source version 1.2.8-xenial0 dpkg-buildpackage: source distribution xenial0 dpkg-buildpackage: source changed by Jeroen Ooms dpkg-source --before-build rapache dpkg-buildpackage: host architecture amd64 dpkg-checkbuilddeps: error: Unmet build dependencies: apache2-dev dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting dpkg-buildpackage: warning: (Use -d flag to override.) debuild: fatal error at line 1376: dpkg-buildpackage -rfakeroot -D -us -uc failed

Is there anybody who can help me please?

I really appreciate any help you can provide.

Roberto

**Comment by jeffreyhorner** [comment]
Hi Roberto,

Looks like ubuntu no longer breaks out the dev files for the prefork mpm.
Plus the prefork mpm comes installed by default (but not configured) with
the apache2 package.

These are the packages I installed to get rapache to compile: apache2
libapreq2-dev apache2-dev

Also, Jeroen put a nice changelog entry in debian/changelog that explains
this:

libapache2-mod-r-base (1.2.8-xenial0) xenial0; urgency=low

  * Remove apache2-mpm-prefork dependency (prefork is now included
    with apache2-dev / apache2-bin)

**Comment by jeffreyhorner** [comment]
And actually it's already a proper ubuntu package in xenial:

$ apt-cache show libapache2-mod-r-base
Package: libapache2-mod-r-base
Priority: optional
Section: universe/web
Installed-Size: 87
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Ondřej Surý <ondrej@debian.org>
Architecture: amd64
Source: rapache
Version: 1.2.7-1
Depends: apache2-api-20120211, apache2-bin (>= 2.4.16), libapreq2-3 (>=
2.13-2), libc6 (>= 2.14), r-base-core
Filename: pool/universe/r/rapache/libapache2-mod-r-base_1.2.7-1_amd64.deb
Size: 24380
MD5sum: 96a5b0063b8d680a658e62ca19195361
SHA1: 871ac3645c3a72c0c1c8f81bd4dc5e1d04e3f8bc
SHA256: 1c852bc6dc10e87c244b3f47c7e17d6b4bfa3fdad61c1a92498e3ebbdc43e462
Description-en: server-side R integration with Apache 2
 This package provides the R module that adds support for embedding
 the R interpreter inside Apache 2 webserver.
Description-md5: 1be630e572081e125ce258dbe3f013eb
Homepage: http://www.rapache.net/
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu

**Comment by jeroenooms** [comment]
Wow I was not aware of that. We should update the manual that folks can now install rapache straight from debian/ubuntu :D

**Comment by rplana6** [comment]
Hi Jeffrey,

What I finally did was:

sudo apt-get update
			sudo apt-get install  libapreq2-dev apache2-dev
			sudo apt-get install libapache2-mod-r-base
sudo git clone https://github.com/jeffreyhorner/rapache
cd rapache
sudo debuild -us -uc
cd ..
sudo dpkg -i libapache2-mod-r-base*.deb

I get some warnings and errors but it seems to work...

Thanks for your help folks!!
Roberto
