### ISSUE TITLE
Ability to kill the apache process from an R script?

### ISSUE THREAD

**Issue by farmdawgnation** [jeffreyhorner/rapache#45]
Hi there -

We're working on integrating rApache in such a way that we can configure and launch instances of it with user provided code. The rub is, we ideally want the ability to kill the Apache process from some R code if some sanity checks fail. Is this possible or even possible to be implemented?

**Comment by jeffreyhorner** [comment]
Is your scenario that you are starting apache from the command line and you want to terminate it if user code fails?

Or are you sending R code to an already running instance and want to terminate the apache child process if the R code fails?

**Comment by farmdawgnation** [comment]
We're starting Apache from the command line, and want it to terminate if user code fails to pass our tests. Our tests will exist in an eval on startup directive and named something like startup.R. I'd like the ability to cause Apache to abort if our checks in that code fail - checks which essentially amount to "Hey check that the file the user wants us to run exists, that R can parse it, and that the function they want exists within it."

**Comment by jeffreyhorner** [comment]
At the moment there's no rapache feature like that, and I'm unsure if apache provides a code level api for such a termination procedure but they might.... how much is this worth to you?

Another alternative is to use a custom apache configuration with a shell script that starts apache in a single process (e.g. with the -X flag if my memory serves), runs the code and sends out a signal of success or failure in some way... not a Unix Signal but a metaphorical signal like writing to the file system or an http code response...

Then if success you can start apache with the user code.

**Comment by farmdawgnation** [comment]
That works, thanks.
