### ISSUE TITLE
Integer overflow for posts over 1GB

### ISSUE THREAD

**Issue by jeroen** [jeffreyhorner/rapache#48]
When using `receiveBin()` (with no arguments) on a payload larger than 1GB:

```
Error in receiveBin() :
  'Realloc' could not re-allocate memory (18446744071562067968 bytes)
```

Looks like an integer overflow happens at [mod_R.c#L2438](https://github.com/jeffreyhorner/rapache/blob/v1.2.8/mod_R.c#L2438). I think we should switch to `R_xlen_t n = xlength(x)` to support long vectors?

**Comment by jeffreyhorner** [comment]
I've attempted a fix with using apr_size_t on the integer types:

checkout the receiveBin-large-payload branch and see if that fixes it.

One line fix, compiled but not tested.

**Comment by jeroen** [comment]
Hm that don't seem to work. It compiles but now the server just gives HTTP 500 for any POST request.

**Comment by jeroen** [comment]
Ah it says: `'Calloc' could not allocate memory (18446744073709551616 of 1 bytes)`

**Comment by jeroen** [comment]
Can we just use `calloc` and `realloc` and `free` instead? The R versions `Calloc` and `Ralloc` always have issues.

**Comment by jeffreyhorner** [comment]
Ok, committed a fix and tested with a 3Gb file.

Try it out.

**Comment by jeffreyhorner** [comment]
Also the Calloc and Realloc calls that R provides are just wrappers around calloc and realloc with convenient  R error handling.

**Comment by jeroen** [comment]
OK that seems to work. I don't really like the `Calloc` and the other S-plus legacy api's but I guess it's fine here. Thanks for looking into it!

**Comment by jeroen** [comment]
I think this is good. Merging into master and tagging a release.
